# This is a basic workflow to help you get started with Actions
name: Itch Build and Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
      branches:
        - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Godot
        uses: solarlabyrinth/action-setup-godot@v2
        with:
          version: 4.5.1-stable

      - name: Setup butler
        uses: remarkablegames/setup-butler@v1

      - name: Create export dir
        run: |
          # Ensure export folders exist both at repo root and inside the project folder
          mkdir -p ./build/web
          mkdir -p ./NameOfGame/build/web

      - name: Open and import files
        run: godot --headless --editor --quit --import .

      - name: Export game for web
        run:  |
          cd NameOfGame
          godot --headless --export-release "Web" ./build/web/index.html

      - name: Upload to itch.io
        run: butler push build/web llunalemon/animal-math-quest:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}